import type { Metadata } from "next";

import "./globals.css";
import Header from "./components/Header";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Google Spreadsheet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  types: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-screen bg-gray-400">
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
